language: generic
sudo: required
services:
- docker
env:
  matrix:
  - TRAVIS_DB=mysql
  - TRAVIS_DB=postgres
  global:
  - ZBOXNOW_VERSION=2.1
  - DOCKERNAME=zboxapp/zboxnow
  - secure: GiWXIeqOY/g3pLsQw0AE1CtL7oW6wp8NSTB+qoQ6OC8+IT02PFdPghyBxEBVveNxMFWtprZoLWuWCiAJtMvOaQsnS7q5ygclry515H8nELwN9TbSEKhMNo32wTMIIvwtpFtrhf0M/QeU/CyML4kj+9o7Ck/Umg7NnzaqKvLH6Z8bRQwOXOF/rT0MIc+I/I+n9n2cPv95C19pb6JJ2diYRIi3DE5fNWyTHGEWUvw4v7Z6BmwUePewXIaIjkaMJV9B8lHLAC6FKS9BoTzdn9phrQ/pnBGLF2pw6e6+TPpLvfF8PhdKiAipRjLX9Q4XTQkK42TNr7R9j5lHkfMZXYCDk9rYizy6Z+4bpsBPA64pmso2GQRs5TJg3pPnBAIQkvwKlez1urWYpe0ACBuXG8k3A8jj8sQIJo0SeWBt4MbpawwFM2X/dZ4h1qn/Vi01LDkP0pNWpZ7o3Fea8pWUvLw2UVxuP0Lg8aovypuzS/W2PDhxm4UzKPLwIMkU/JSF3zB6f0nm1iDcPVePyujGPEWsM6d5UbvBHbda46Lzp5OgHhUvj85Qrlayz1btlhDwpKPZU90mLoro9W6pPSxvWvJpZBymKUxPuXGrlZhhZ2AQXOOIUyU5uFIEub8n3uidwwZ83qMGpnoLEyqADO0eh6y3PyWya4k0GothD0vloXFPmec=
  - secure: ZwYbdQf6uF8e8FCaO1XtBR2zl1pS8jkaK+uJU0YeiK37G1MMRR6M1No/uV5I6pfp7/Gwb+hW957+8pIZzRvwNMADuaIN0LTsYK3Tc17fIoGaPX+Ky08F3JJst4i7jx0WkNY95N/elLE7XGJheLeS30Z+BV9kNFkG3bO6os9xJ0JDezH9c4JudHu4zlObCMQrQSYN9zTns5OGitt9iKrKuKOdQBaP+1vLV4D/UuoMN5lCTnsId7jmR/z1rOmS2weQd79cue/7SXPdskyh7SgFoboXUicKYXlvRGsSK/jor69zsafa/VCNI73BXSNI0PmueZwN+VBsW3Y6LYTV7P+pIZnGpHNv9J80OLHw+0Af/JNTHY3qWpH+Ut1NpbtO8ZdeskTWqSvTPjJfwewcb95pOA93z9cZYZOusgn3YVwhWEunpYacXVl30d+f1GDyGOy9EjmlG+e36OxnX4A53w5BKR6DwvW3LQpH54l6EkDiSFpmRKDBaqdmJVRttjmnBS01IwdVzYabRxDMSpxoQOVGywtJfa/Zc5d21Z6OTXQ6gM8LbcLmjrtTwv9lOZ+PhWn5mR04Rc+Xoh4MS5mOMMq17MGXIPOgkwj4U6cvlzy0iVJT7Zw2ym6z4+aWjh11LvkFhVkvIk2nBqxDJWi/PXbpUa/nTARXTdTcVwTQlr+ke0Q=
  - secure: ohdB6FAPQxfnvoESewhHFmTOxUgmmtLLkUiI7+8xOjON0ekV9PoxSuKa+J5fb6Y70pSZRwtyaO2zVXWTU9vceskPvzH54vnlZylaF0yHaIUS2IBAnJSnRsNAhzrG1maQzTA+HOruptiFRzJxXun32R3YrnS6y7DeLeWiXfNiKQzl+zkjpvtO4jtmsMi6rJNdhuw5BNHUBlU195lF/SZwIpy8wu8dkoDIUBdyAIvmHtijW9Tew69UQKT6X7F+38wXTqu5HTcVZCl6oOxbSWO3ZI8+nuhw5B1o7cQkbQAKb369jsyYPOGpdLbyIexCSK0sARthFdyeFxhqoO7FB7wzZZK84CLnCEFi7KxqI8mE4G/u0TOfFyGNPVwDSOqaUFp5Zrd8b/Ooo3AxYGUWibAjnEGzW6iBtJpBe8Bs0VwsWkn98mNW7p3s02NlzB9fyfU9CLIvnGnSppuTOCKloBF9RwzxB2pNl9zQzGN1KIzjGVzM/0FOHfko36Mg7LgaNiQCepXCKz9BbWzC7Ax+6lNim+aEqm/LbxX/Lqu7x46vWHPJtvDfAFlmQzJQILN0lc3IApnkHXhF/NP9LrHnTogT9v3q+R6zP+tp2Ta8jRiAbKPnTrL63XKyxpkP0eBrZN292qkIayrGzcGrtwWS12gr7iJDvYH2NKhjP1WmWvuB6i8=
before_install:
- docker run --name zboxnow-mysql -e MYSQL_ROOT_PASSWORD=zbtest -e MYSQL_USER=zbuser
  -e MYSQL_PASSWORD=zbtest -e MYSQL_DATABASE=zboxnow -d -p 3306:3306 mysql:5.7
- docker run --name zboxnow-postgres -e POSTGRES_USER=zbuser -e POSTGRES_PASSWORD=zbtest
  -d postgres:9.4
- sleep 10
- docker exec zboxnow-postgres psql -c 'create database zboxnow ;' -U postgres
- docker exec zboxnow-postgres psql -c 'grant all privileges on database "zboxnow"
  to zbuser ;' -U postgres
script: make dist-travis
addons:
  hosts:
  - 127.0.0.1 dockerhost
before_deploy:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - sudo rm -rf ./api/data
  - sudo rm -rf ./logs
  - sudo rm -rf **/zboxnow.log
  - docker build -t $DOCKERNAME:$ZBOXNOW_VERSION -f docker/prod/Dockerfile .
  - docker tag -f $DOCKERNAME:$ZBOXNOW_VERSION $DOCKERNAME:latest
deploy:
- provider: script
  skip_cleanup: true
  script: make deploy
  on:
    repo: ZBoxApp/platform
    branch: zbox
    condition: "$TRAVIS_DB = mysql"